<a href="https://colab.research.google.com/github/Ansalnakhan/Advanced-computing-lab/blob/main/experiment%208%20make%20regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
from sklearn.neural_network import MLPRegressor

In [26]:
from sklearn.datasets import make_regression

In [28]:
X, y = make_regression(n_samples=20, n_features=3, random_state=1)

In [29]:
import numpy
numpy.shape(X)

(20, 3)

In [33]:
y

array([ 1.07959072e+01, -8.70682179e+01, -2.58767057e+02,  6.19892631e+00,
       -2.98545349e+02, -3.41308348e+02,  1.97726219e+02,  4.12847206e+01,
        1.04799507e+02, -7.91156844e+01, -7.13581176e+01, -1.31498582e+02,
        2.61014090e+02,  4.36391991e+01, -3.02888689e+02,  9.70851107e-02,
       -1.08042089e+02,  1.46616705e+02, -1.43720803e+02,  6.92793587e+01])

In [34]:

from sklearn.model_selection import train_test_split
X, y = make_regression(n_samples=20, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [35]:
regr = MLPRegressor(random_state=1, max_iter=500).fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [36]:
regr.predict(X_test[:2])


array([ 9.56184585, 34.87062855])

In [41]:
regr.score(X_test, y_test)

0.05892633642404144

In [42]:
y_pred=regr.predict(X_test)

In [44]:
y_pred

array([  9.56184585,  34.87062855,   1.63316684,  -4.49216823,
       -53.98969787])

In [45]:
from sklearn import metrics as m

In [52]:
print(m.r2_score(y_test, y_pred))

0.05892633642404144
