<a href="https://colab.research.google.com/github/Ansalnakhan/Advanced-computing-lab/blob/main/EXPERIMENT%209/CALIFORNIA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
from sklearn.neural_network import MLPRegressor

In [85]:
from sklearn.datasets import make_regression

In [86]:
X, y = make_regression(n_samples=20, n_features=3, random_state=1)

In [87]:
import numpy
numpy.shape(X)

(20, 3)

In [88]:
y

array([  -7.00766922,  -23.32252002,   25.0705527 , -112.30734132,
         40.47679433,  -75.74394066,  -87.23159723,   38.65979395,
         86.37807751,   -6.20444587,  -84.33111343,   15.51804759,
        130.9822354 ,    4.31361666,  103.77692959,  113.07869181,
         27.42693388,  -65.30169504, -112.504787  ,  -30.92216021])

In [89]:

from sklearn.model_selection import train_test_split
X, y = make_regression(n_samples=20, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [90]:
regr = MLPRegressor(random_state=1, max_iter=500).fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [91]:
regr.predict(X_test[:2])


array([ 9.56184585, 34.87062855])

In [92]:
regr.score(X_test, y_test)

0.05892633642404144

In [93]:
y_pred=regr.predict(X_test)

In [94]:
y_pred

array([  9.56184585,  34.87062855,   1.63316684,  -4.49216823,
       -53.98969787])

In [95]:
from sklearn import metrics as m

In [96]:
print(m.r2_score(y_test, y_pred))

0.05892633642404144


In [97]:
from sklearn.datasets import fetch_california_housing

In [98]:
data= fetch_california_housing(as_frame=True)

In [116]:
X=data.data

In [117]:
Y=data.target

In [118]:
import numpy

In [119]:
numpy.shape(X)

(20640, 8)

In [121]:
Y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHouseVal, Length: 20640, dtype: float64

In [122]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=1)

In [123]:
regr = MLPRegressor(random_state=1, max_iter=300).fit(X_train, Y_train)

In [124]:
regr.predict(X_test[:2])

array([2.23825103, 1.21864776])

In [125]:
regr.score(X_test, Y_test)

0.5261964220149624

In [126]:
Y_pred=regr.predict(X_test)

In [127]:
Y_pred

array([2.23825103, 1.21864776, 2.45076773, ..., 1.14738946, 3.09329991,
       1.79619069])

In [128]:
from sklearn import metrics as m

In [129]:
print(m.r2_score(Y_test, Y_pred))

0.5261964220149624
